import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  ShadingType,
  TableRow,
  TableCell,
  Table,
  WidthType,
} from 'docx'
import { saveAs } from 'file-saver'
import { DayPlan } from '@/types/itinerary'

const TRANSPORT_LABEL: Record<string, string> = {
  walk: '🚶 Walk', subway: '🚇 Subway', bus: '🚌 Bus', taxi: '🚕 Taxi',
  train: '🚆 Train', bike: '🚲 Bike', car: '🚗 Drive', boat: '⛴️ Boat',
}

export async function exportItineraryToWord(itinerary: DayPlan[], destination: string) {
  const children: (Paragraph | Table)[] = []

  // ── Cover title ──────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      text: `✈️  ${destination} Travel Itinerary`,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Plotted  ·  ${itinerary.length} day${itinerary.length > 1 ? 's' : ''}`,
          color: '888888',
          size: 22,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
  )

  // ── Days ─────────────────────────────────────────────────────────────────
  for (const day of itinerary) {
    // Day heading
    children.push(
      new Paragraph({
        text: `Day ${day.day}`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 6, color: '6366f1' },
        },
      }),
    )

    for (let i = 0; i < day.places.length; i++) {
      const place = day.places[i]

      // Place name row
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${i + 1}.  `, bold: true, color: '6366f1', size: 26 }),
            new TextRun({ text: place.name, bold: true, size: 26 }),
            new TextRun({ text: `    ${place.time}  ·  ${place.duration}`, color: '888888', size: 22 }),
          ],
          spacing: { before: 240, after: 80 },
        }),
      )

      // Note / description
      if (place.note) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: place.note, color: '444444', size: 22, italics: true }),
            ],
            indent: { left: 480 },
            spacing: { after: 100 },
          }),
        )
      }

      // Transport to next stop
      if (place.transportToNext && i < day.places.length - 1) {
        const label = TRANSPORT_LABEL[place.transportToNext.mode] ?? '➡️'
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `  ${label}  ${place.transportToNext.duration}`,
                color: '6366f1',
                size: 20,
              }),
            ],
            indent: { left: 480 },
            spacing: { before: 60, after: 60 },
            shading: { type: ShadingType.CLEAR, fill: 'EEF2FF' },
          }),
        )
      }
    }
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'Have a wonderful trip! 🌍', color: '888888', size: 20, italics: true }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 800 },
    }),
  )

  const doc = new Document({
    sections: [{ properties: {}, children }],
    styles: {
      paragraphStyles: [
        {
          id: 'Title',
          name: 'Title',
          run: { size: 52, bold: true, color: '1e1b4b' },
        },
        {
          id: 'Heading1',
          name: 'Heading1',
          run: { size: 32, bold: true, color: '4338ca' },
        },
      ],
    },
  })

  const blob = await Packer.toBlob(doc)
  const filename = `${destination.replace(/[^a-z0-9]/gi, '_')}_itinerary.docx`
  saveAs(blob, filename)
}
